algoritmo "Algoritmo de média aritmética"
var
N1, N2, M: Real
inicio
      Escreval ("Olá, eu sou um algoritmo calculador, digite seus números abaixo.")
      Escreva ("Digite o primeiro número:")
      Leia (N1)
      Escreva ("Digite o segundo número:")
      Leia (N2)
      M <- (N1 + N2) / 2
      Escreva ("A média aritmética entre os números ", N1, " e ", N2, " é: ", M)
      fimalgoritmo
