algoritmo "TorneioDeFutebol (Incompleto)"
var
   Time1, Time2, Time3: Caractere
   T1, T2, T3, C: Inteiro
inicio
      Para C <- 1 ate 3 faca
           Escreva ("Time",C, ": ")
           Leia (Time1)
      FimPara

      Para T1 <- 1 ate 3 faca
           Para T2 <- 1 ate 3 faca
                Para T3 <- 1 ate 3
                     Escreval (Time1, Time2, Time3)
                FimPara
           FimPara
      FimPara
fimalgoritmo